### ISSUE TITLE
春松客服，全渠道智能客服系统

### ISSUE THREAD

**Issue by Samurais** [hpgary/MyAlice#2]
推荐同样是面向智能客服的项目，交流学习

https://github.com/chatopera/cosin

**Comment by hpgary** [comment]
@Samurais  自己的产品，自己官网不用？上去说半天没有任何回复-

**Comment by Samurais** [comment]
你发的我们看到了，我们一直在用。

**Comment by hpgary** [comment]
@Samurais  官网首页没有使用？https://www.chatopera.com/   点开变成留言了

**Comment by hpgary** [comment]
https://www.chatopera.com/   官网好像已经没有在线客服按钮了，目前只能申请试用    感谢推荐
